### ISSUE TITLE
CSL: Position "ibid" isn't tested well.

### ISSUE THREAD

**Issue by Goldmensch** [typst/hayagriva#122]
In my csl file I have the following choose:
```xml
  <macro name="display_full">
      <choose>
        <if position="ibid"><text term="ibid."/></if>
        <else-if position="subsequent"><text macro="short"/></else-if>
        <else-if type="webpage"><text macro="webpage"/></else-if>
        <else-if type="book"><text macro="book"/></else-if>
      </choose>
  </macro>
  ```
  
  But when I cite the exact same source with the same locator, the subsequent position is shown, instead of `ibid` or `ebd.` in my case (german):
  
![image](https://github.com/typst/hayagriva/assets/47005420/ab38e71d-ca1a-4952-942a-7a5c3e8e2d95)

According to the specification, the position should be "ibid" for the cite in footnote 18:
> Preceding cite does have a locator: if the current cite has the same locator, the position of the current cite is “ibid”. If the locator differs the position is “ibid-with-locator”. If the current cite lacks a locator its only position is “subsequent”.

https://docs.citationstyles.org/en/stable/specification.html#choose

**Comment by DerDrodt** [comment]
Can you provide the full CSL file and your typst example? I want to test it.

**Comment by Goldmensch** [comment]
My full csl file ist https://pasty.lus.pm/7EFWBZ
I've also created an example project for you: https://typst.app/project/riYKg0JpjFOFRWrk2avw3P

**Comment by Goldmensch** [comment]
@DerDrodt is there any chance that this gets fixed until February 6/7?

**Comment by reknih** [comment]
None unless you want to use Typst's development build. We plan a release for the second half of February.

**Comment by DerDrodt** [comment]
> @DerDrodt is there any chance that this gets fixed until February 6/7?

I plan to look at it tomorrow but I would not get my hopes up. All the ibid-stuff is new to me and I don't know the code well.

**Comment by Goldmensch** [comment]
> > @DerDrodt is there any chance that this gets fixed until February 6/7?
> 
> 
> 
> I plan to look at it tomorrow but I would not get my hopes up. All the ibid-stuff is new to me and I don't know the code well.

Alright. 
But thanks already!

**Comment by DerDrodt** [comment]
That was (hopefully) easier than expected.

**Comment by Goldmensch** [comment]
@DerDrodt I just tried your fix, but that resulted in changing every use of a locator in ebd. instead of just them who are equal. 
![image](https://github.com/typst/hayagriva/assets/47005420/c4977824-f919-42e5-91f4-1db6e58eb438)
Now becomes 
![image](https://github.com/typst/hayagriva/assets/47005420/71137fe7-651b-4508-9141-8eecf20f0e22)
But actually there should be an ibid nowhere. (ebd.)

Another example:
![image](https://github.com/typst/hayagriva/assets/47005420/2b010d8d-ef89-4f3a-950a-b1f114d559d5)
becomes 
![image](https://github.com/typst/hayagriva/assets/47005420/cc32d0dd-021a-45c9-a30f-cbee80a30969)
But only the last 3 lines should be ibid. (ebd.)

**Comment by DerDrodt** [comment]
That's not good and did not happen for my tests. I will look into it.
