### ISSUE TITLE
Does Hayagriva use CSL internally?

### ISSUE THREAD

**Issue by retorquere** [typst/hayagriva#132]
It looks like Hayagriva uses CSL styles, does that mean it uses CSL as its internal model, and is the [yaml format](https://github.com/typst/hayagriva/blob/main/docs/file-format.md) then just syntactic sugar over CSL (since CSL styles won't be able to use anything but what's expressible in CSL)?

I have a [user request](https://github.com/retorquere/zotero-better-bibtex/issues/2711) for Hayagriva YAML support for Zotero, but if Hayagriva uses CSL internally, it seems more productive to have it also accept CSL as a input format, rather than the conversion pipeline Zotero -> CSL -> Hayagriva -> CSL.

**Comment by laurmaedje** [comment]
The data model is independent, but the formatting is dependant. Supporting CSL as input would be feasible for hayagriva.

**Comment by retorquere** [comment]
Right, I understand the data model can be independent, but no styles from https://citationstyles.org/ will know what to do with data that cannot be expressed in CSL fields; if that is true there wouldn't be much use in adding non-CSL-conforming data.

**Comment by retorquere** [comment]
The yaml formats aren't the same, they express the same information in very different ways. The way it seems to me, hayagriva is essentially a preprocessor for CSL-JSON.

**Comment by reknih** [comment]
We eventually also plan to support writing citation styles in the Typst language using the data in the Hayagriva data model directly, so it has its place. CSL-JSON is currently accepted, but only used in the test suite. The problem is that Hayagriva does not allow mixing of CSL-JSON and its native entries (and BibLaTeX, which gets converted to native Hayagriva) in a bibliography. I'd like to fix that before we expose CSL-JSON to our users.

**Comment by retorquere** [comment]
When that moment comes, ping me and I'll see what I can do for hayagriva support.

**Comment by retorquere** [comment]
> We eventually also plan to support writing citation styles in the Typst language using the data in the Hayagriva data model directly

Has this ever come about? Because the bibtex - CSL route involves [unnecessary risk of information loss](https://retorque.re/zotero-better-bibtex/exporting/pandoc/index.html), so I would argue it would serve the user best to at least offer a straight CSL path. It seems to me that until citeproc-csl is replaced in typst, any format other than raw CSL-JSON carries this unnecessary risk.

**Comment by YDX-2147483647** [comment]
(Perhaps typst/typst#2924 is a better place for discussions; #485 is also related.)

**Comment by retorquere** [comment]
Alright, I have commented there.
