### ISSUE TITLE
[Question] Why is it named after a Hindu god?

### ISSUE THREAD

**Issue by stefanocoretta** [typst/hayagriva#136]
Hi! Thanks for working on Typst, I'm having fun learning it.

Just out of curiosity: Why is the bibliography tool named after a Hindu god?

**Comment by reknih** [comment]
We were looking for a topical and meaningful name for the crate. When I came across the saga of Hayagriva, I thought that it plays into what we want to empower our users to do:

> Symbolically, the story [of Hayagriva] represents the triumph of pure knowledge, guided by the hand of Divinity, over the demonic forces of passion and darkness.

From https://en.m.wikipedia.org/wiki/Hayagriva

Like in the story we want to give our users the tools to relay their knowledge and experience by standing of the shoulders of giants (with the literature in their field).

Of course, no disrespect to Hindus or followers of Hayagriva was ever intended.

**Comment by stefanocoretta** [comment]
Thanks for the explanation. :) I would say that if you explicitly mention the story and the reason behind choosing that name will show that the choice was made with cultural understanding in mind.
