### ISSUE TITLE
Additional page gets displayed when only one is specified in the bibliography entry

### ISSUE THREAD

**Issue by xkevio** [typst/hayagriva#142]
Since #104, I believe, single page numbers in the `pages` field (`.bib`) or in the `page-range` field (`.yml`) no longer render correctly. It always adds the following page as well, turning `p. 103`, for example, into `p. 103 -- 104`. Note that, whatever the CSL style uses as a word for `page` does not get pluralized.

This can be reproduced with just about any simple entry and many styles, like the default IEEE.
https://typst.app/project/rxfSNvq9A61PlAievgf9sa

**Comment by xkevio** [comment]
@Drodt / @DerDrodt, maybe you know what caused this since you worked on the recent page range commits.

**Comment by DerDrodt** [comment]
Yes, I have a quick fix in #145.

**Comment by MangoIV** [comment]
this problem persists at least when rendering MLA9. e.g. 
`page-range: 33` gets rendered as `p. 33-34`

**Comment by xkevio** [comment]
> this problem persists at least when rendering MLA9. e.g. `page-range: 33` gets rendered as `p. 33-34`

Are you rendering with just hayagriva and if so, main commit version or v0.5.3? Or with Typst?

**Comment by MangoIV** [comment]
I have tried with both `typst` cloud and standalone `typst 0.11.1`. I have check typst, it should have had the patch in the last release.

**Comment by MangoIV** [comment]
I would also be happy about a hacky fix for the moment :P

**Comment by xkevio** [comment]
I assume by typst cloud you mean the webapp? Then both are currently on v0.11.1 and that version — trust me, I've checked — did not include this bugfix in particular (cc: @laurmaedje, you mentioned there was some reason for it)

**Comment by MangoIV** [comment]
I see ~ maybe they didn't bump "citationberg"? :P

**Comment by MangoIV** [comment]
I'll see if I can quickly :tm: build from source.

**Comment by xkevio** [comment]
> I'll see if I can quickly ™️ build from source.

Not sure if hayagriva was bumped yet on typst main (Cargo.toml says its still 0.5.3 which doesnt have the fix). I assume the dependencies will be bumped soon as we get closer to v0.12. You can however still build from source, you just have to point the hayagriva entry in the Cargo.toml to this repository.

**Comment by MangoIV** [comment]
building from source worked just fine. thank you <3
