### ISSUE TITLE
Narrative citation (`form: "prose"`) for `apa.csl` shows too many authors

### ISSUE THREAD

**Issue by rikhuijzer** [typst/hayagriva#149]
According to the Typst [guide for LaTeX users](https://typst.app/docs/guides/guide-for-latex-users/), the Typst equivalent of `\textcite` is `#cite(<key>, form: "prose")`. I've been using that, but it looks like it isn't following the CSL file correctly for `apa.csl`. It shows 4 authors for me in the full text version while using APA 7, while the APA 7 CSL would abbreviate this to "Author et al.".

I've added a reproducible example below. This is as narrow as I could get now. It needs some more digging to find the root cause.

# Reproducible Example

The file `mwe.ty:`
```typst
Lorem ipsum @alfa2000.

But also #cite(<alfa2000>, form: "prose").

#bibliography("mwe.bib", style: "apa")
```

with bibliography file `mwe.bib:`
```bib
@article{alfa2000,
    author = {Alfa, A and Bravo, B and Charlie, C and Delta, D},
    title = "Why Most Published Papers are Full of Text",
    year = 2000
}
```
will generate:

> Lorem ipsum (Alfa et al., 2000).
>
> But also Alfa, Bravo, Charlie, & Delta (2000).
>
> ## Bibliography
>
> Alfa, A., Bravo, B., Charlie, C., & Delta, D. (2000). _Why Most Published Papers are Full of Text._

But this second sentence should have been:

> But also Alfa et al. (2000).

# LaTeX

I've loaded [the latest official `apa.csl` file](https://github.com/citation-style-language/styles/blob/v0.0.409/apa.csl) into LaTeX too. There the output is correct. With the same `bib` file, the text
```latex
lorem ipsum \textcite{alfa2000}.
```
correctly generates

> lorem ipsum Alfa et al. (2000).

**Comment by laurmaedje** [comment]
Similar to https://github.com/typst/hayagriva/issues/141 (probably same cause).

The et-al handling had a regression in Typst 0.11 / Hayagriva 0.5.2.

**Comment by rikhuijzer** [comment]
Thanks @laurmaedje. Looks the same to me indeed. I'll close this issue
