### ISSUE TITLE
BibLaTeX note field not mapped to CSL note variable correctly

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [typst/hayagriva#162]
### Description

I'm trying to use a custom CSL file to display a bibliography in Typst. However, it seems the `note` variable in CSL is not correctly populated with the `note` field of a Biblatex entry.

A reproduction URL has been shared to demonstrate a MWE that exhibits this issue. The `main.typ` simply creates a bibliography with the `mwp.bib` Biblatex file and `ieee.cls` CSL file. The Biblatex file contains just one entry with a `note` field (and other dummy entries). The IEEE CSL file is sourced from [here](https://github.com/citation-style-language/styles/blob/master/ieee.csl), and contains a commented modification on lines 359 and 360, demonstrating that the `title` variable is displayed, but the `note` variable isn't.

Edit: updated the project link

### Reproduction URL

https://typst.app/project/rjXQrnuitjqc0tdVdyL7qK

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by reknih** [comment]
I'm afraid that there is no totally satisfactory solution here. See #220.
