### ISSUE TITLE
Allow the use of CSL's `number-of-pages` number variable

### ISSUE THREAD

**Issue by Andrew15-5** [typst/hayagriva#169]
In [BibTeX](https://www.bibtex.com/g/bibtex-format/) it looks like there is only the `pages` field and in [CSL](https://docs.citationstyles.org/en/stable/specification.html#number-variables) there are `page` and `number-of-pages`.

When I was testing Hayagriva is Typst with a custom CSL style I noticed that apparently Hayagriva's `page-total` is mapped to CSL's `number-of-pages`, but `number-of-pages` directly in the YAML file is not accessible. I don't see a reason to create a 3rd name for the same thing just to confuse CSL style developers. Why `page-total` is not named `number-of-pages`? I used `volume` until this moment, because I thought that `number-of-pages` just isn't supported yet. But it is, you just have to use non-CSL-standard `page-total`.

I want to either be allowed to use both fields (one is described [here](https://github.com/typst/hayagriva/blob/main/docs/file-format.md), and the other is inherited implicitly from CSL standard) that will map to the same CSL field/variable (i.e., aliases), or rename `page-total` to `number-of-pages`.

**Comment by reknih** [comment]
[Hayagriva's data model is distinct from CSL](https://github.com/typst/hayagriva/issues/132#issuecomment-2405196129) because we expect to offer creating citation styles in Typst using it in the future.

@laurmaedje and I feel that CSL contains a few sub-par design choices which we do not want to grandfather into that system.

**Comment by Andrew15-5** [comment]
I don't think that `number-of-pages` is a sub-par design choice. I think that it's more descriptive and slightly easier to understand what it refers to. But I **at least** expect to see a note about the CSL to Hayagriva field mapping in https://github.com/typst/hayagriva/blob/main/docs/file-format.md. This is so that CSL developers wouldn't fall into the same pitfall I did when started using Hayagriva.

**Comment by Andrew15-5** [comment]
> It’s not about the naming page-total vs number-of-pages. It’s that hayagriva is a completely separate data model and it existed before the CSL integration and it will likely survive CSL being the main way to format bibliographies in Typst. Thus, we don’t want to rename things just to match CSL.

I already forgot that CSL was _integrated_ at some point. Yeah, I guess renaming is not the way.

> That aside, I think it’s good that the term starts with „page“ rather than „number“. In an ordered list, it is easier to find.

You have a point there.

> I would also like to note that your bold „at least“ comes across as quite entitled.

I think it's natural for people to have different expectations. I'm just putting stress at what _I_ expect as a bare minimum solution/fix. I'm not sure what's entitled about that (or what it exactly mean here).

But regardless, what about the mapping? Was it even considered at some point? I think it's a good documentation improvement (from a migration/dev standpoint). I just don't know where else would be a good place to include such mapping notes other than directly in the list of fields defined as tables (so you would add another row to some fields).
