### ISSUE TITLE
The `note` field is omitted when converting BibTeX to Hayagriva 

### ISSUE THREAD

**Issue by tomas-vl** [typst/hayagriva#182]
Input `t.bib`:
```
@book{test_1,
    note = {This is a test!}
}
```
Expected output:
```
test_1:
  type: book
  note: "This is a test!"
```
Real output:
```
test_1:
  type: book

```
I've notices that when converting a BibTeX file into a Hayagriva file, the `note` field is omitted. (I ran the command `hayagriva t.bib` using Hayagriva v0.5.3. This bug is also carried into Typst: CSL styles which use the `note` field cannot use it when the user is working with a BibTeX file directly.)

**Comment by PgBiel** [comment]
I believe this has been fixed with #220.
