### ISSUE TITLE
Hayagriva does not recognize `editor-translator` term

### ISSUE THREAD

**Issue by poopsicles** [typst/hayagriva#187]
I wanted to edit a CSL style in order to make "et al." italics (ended up just using a show rule in Typst for this) and tried to use the default `apa.csl` from the citation-style-language/styles repo [here](https://github.com/citation-style-language/styles/blob/master/apa.csl).

However, using it with the CLI panics when trying to deserialise the XML:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/2fb4d11c-f620-4422-af9f-09d616a66c38">

I also tried to look for the "default" CSL file used by this repo, but couldn't find it unfortunately...

**Comment by poopsicles** [comment]
forgot to show the output as text:

```sh
$ hayagriva --version
Hayagriva CLI 0.5.3

$ hayagriva references.bib cite --key structured -s american-psychological-association
Dijkstra, E. W., Dahl, O. J., & Hoare, C. A. R. (1972). Structured programming. Academic Press Ltd.

$ hayagriva references.bib cite --key structured --csl /Users/fum/Downloads/apa.csl
thread 'main' panicked at /Users/fum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hayagriva-0.5.3/src/main.rs:463:51:
CSL file malformed: Custom("data did not match any variant of untagged enum Term")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PgBiel** [comment]
This appears to be because the APA styles specify the (new?) term `editor-translator` in `<locale>...</locale>` as well as `editortranslator`, while we only support the latter. This is also the reason why CI is currently failing.
