### ISSUE TITLE
Consider creating a ```title-short``` reference field for subsequent footnote entries (Hayagriva YAML)

### ISSUE THREAD

**Issue by ironupiwada** [typst/hayagriva#213]
Currently, Hayagriva YAML supports only the ```title``` reference field. This is adequate for author-date references. However, when transferred from BibLaTeX files, Hayagriva YAML loses the ```shorttitle``` fields, whereas many footnote styles actually use them in CSL for subsequent entries. Moreover, there is no ```shorttitle``` in the Hayagriva documentation. Therefore, I suggest implementing a kind of this field in Hayagriva.

The code for improved entries would look like:
```Winnicka_1968_2018:
  type: book
  title: "1968. Czasy nadchodzą nowe"
  title-short: "1968"
  author:
  - Winnicka, Ewa
  - Łazarkiewicz, Cezary
  date: 2018
  publisher: 'Agora'
  location: 'Warszawa'
```

EDIT: Whereas Hayagriva supports such a code:

```
title:
      value: "1968. Czasy nadchodzą nowe"
      short: "1968"
```

CSL treats it as a shorthand, not as a shorttitle. The difference is that the ```short``` parameter shortens every footnote AND bibliographic entry, instead of leaving the full title in the first footnote and in the bibliography.

**Comment by ironupiwada** [comment]
I installed `hayagriva` (main release) and nothing changed. Consider the following code in Hayagriva:

```
Winnicka_1968_2018:
  type: book
  title: 
    value: '1968. Czasy nadchodzą nowe'
    short: '1968'
  author:
  - Winnicka, Ewa
  - Łazarkiewicz, Cezary
  date: 2018
  publisher: 'Agora'
  location: 'Warszawa'
```

and biblatex:

```
@book{Winnicka_1968_2018,
	author = {Winnicka, Ewa and Łazarkiewicz, Cezary},
	date = {2018},
	language = {pl},
	location = {{Warszawa}},
	publisher = {{Agora}},
        shorttitle = {1968},
	title = {1968. Czasy nadchodzą nowe},
}
```

Regardless of which bibliography I use (YAML or Bib), with `shorttitle` in YAML the result is the following:

![obraz](https://github.com/user-attachments/assets/86219065-47c1-4e37-aa8e-419dc1ab3967)

And the bibliographic entry shows:

![obraz](https://github.com/user-attachments/assets/eef8121d-7311-4ebc-87e2-84cd42e7d922)

(note that I use the `chicago-fullnote-bibliography-with-ibid` style).

The Bib file, in turn, leads to the following outputs:

![obraz](https://github.com/user-attachments/assets/8d77bd3b-702e-4d26-92d4-1f1b4fc19e2b)

and the bibliographic entry shows:

![obraz](https://github.com/user-attachments/assets/209355e9-7106-47c4-a603-69dd1183fe15)

Here it is clear that Hayagriva either prints only shorttitles as outputs (which is an evident error for chicago-like notes) or does not print shorttiles at all.

**Comment by ironupiwada** [comment]
OK, after compiling with the latest main release of `typst` (with Hayagriva 0.6), it works properly (even on custom CSL templates, as attached below). Thanks!
![obraz](https://github.com/user-attachments/assets/4e3eed55-f2ce-4557-b3d1-5f1d2619e069)

**Comment by PgBiel** [comment]
Ah, I thought you were using hayagriva main in your previous comment. Note that the hayagriva CLI isn't used by typst, so installing it in your system doesn't change the hayagriva version used by typst (it includes its own copy of hayagriva). I was proposing testing using the hayagriva CLI directly, e.g. `hayagriva bib.yml cite --key <name> --style chicago-notes` to see what it produces, but I now see that I misunderstood your problem, so you wouldn't be able to test it just with the CLI. I'm glad it's solved!
