### ISSUE TITLE
[Question] How to translate this?

### ISSUE THREAD

**Issue by ichxorya** [typst/hayagriva#42]
Title. I don't understand the structure of this project. As the only lang file (?) src/lang/en.rs is available, I can't get much insight from this.

**Comment by laurmaedje** [comment]
At this point, it probably doesn't make much sense to look into translating Hayagriva. We're investigating how to best integrate CSL etc. and that will probably include a large rework of hayagriva.

**Comment by ichxorya** [comment]
Thanks, I'm using this for typst citation in a full Vietnamese document. Mixed-in English is unavoidable, so I would love to translate this ASAP!

**Comment by reknih** [comment]
Hayagriva now uses CSL locales with 0.9.0. The Vietnamese locale is included in the archive.

**Comment by ichxorya** [comment]
![image](https://github.com/typst/hayagriva/assets/26222301/dea28f09-00f9-4b55-bb2d-387c4804de2b)

As you can see, my full-Vietnamese document has been mixed with "Available at". How could I help to change this?

**Comment by zepinglee** [comment]
> As you can see, my full-Vietnamese document has been mixed with "Available at". How could I help to change this?

`#set text(lang: "vi")`

**Comment by ichxorya** [comment]
> > As you can see, my full-Vietnamese document has been mixed with "Available at". How could I help to change this?
> 
> `#set text(lang: "vi")`

Nothing changed. I have added that in the main document, the tempate, and even the yaml file
