### ISSUE TITLE
Harvard Referencing support

### ISSUE THREAD

**Issue by Suyashtnt** [typst/hayagriva#43]
A lot of schools (Including mine) use Harvard referencing. It would be nice if hayagriva/typst could support the referencing style.

I've looked into implementing it myself, but I have no idea how hayagriva so it's probably going to take some time to implement it

**Comment by reknih** [comment]
Hayagriva now bundles `harvard-cite-them-right` and `elsevier-harvard`. Do any of these styles work for you?

**Comment by Suyashtnt** [comment]
Yep cite them right is the one I'm looking for. TYSM
