### ISSUE TITLE
Feature Request : Visual Code citation picker extension

### ISSUE THREAD

**Issue by Iriamu19** [typst/hayagriva#55]
Hi,

It could be great to have a citation picker extension for Visual Code like this one for example [Zotero](https://github.com/mblode/vscode-zotero) or [this one for markdown file and bibtex file](https://github.com/notZaki/PandocCiter).

Best regards, you're doing a great job.

**Comment by laurmaedje** [comment]
This is a cool idea and would be a nice community project, but it's out of scope for hayagriva itself.
