### ISSUE TITLE
Incorrect parsing of author names in .bib file

### ISSUE THREAD

**Issue by jevdplas** [typst/hayagriva#61]
I copied the following reference from DBLP (omitting some fields):
```@article{denning_denning_1977,
  author       = {Dorothy E. Denning and
                  Peter J. Denning},
  title        = {Certification of Programs for Secure Information Flow},
  journal      = {Commun. {ACM}},
  volume       = {20},
  number       = {7},
  pages        = {504--513},
  year         = {1977},
  doi          = {10.1145/359636.359712},
}
```

For this reference, I found two unexpected behaviours (which also differ from how LaTeX processes it).

(1) Using the above format, the first author is displayed as `D.E.D.` in the PDF. Thus, unexpectedly, the last name of the first author is abbreviated as well.
(2) When trying to avoid this, I put the authors in the `lastname, firstname` format as follows: 

```@article{denning_denning_1977,
    author       = {Denning, Dorothy E. and
                    Denning, Peter J.},
    title        = {Certification of Programs for Secure Information Flow},
    journal      = {Commun. {ACM}},
    volume       = {20},
    number       = {7},
    pages        = {504--513},
    year         = {1977},
    doi          = {10.1145/359636.359712},
  }
```
However, now, there appears some odd spacing in the final PDF which appears to be originating from the newline between the two authors that is not removed.

The following reference works as expected:

```@article{denning_denning_1977,
  author       = {Denning, Dorothy E. and Denning, Peter J.},
  title        = {Certification of Programs for Secure Information Flow},
  journal      = {Commun. {ACM}},
  volume       = {20},
  number       = {7},
  pages        = {504--513},
  year         = {1977},
  doi          = {10.1145/359636.359712},
}
```
However, I'd also expect that the first two formats work as well, like they do in LaTeX.

**Comment by jevdplas** [comment]
Additional information: for case (2) I noticed that there not only is odd spacing (e.g., a newline indeed being added), but that the info of the different authors can/is also being scrambled.

**Comment by reknih** [comment]
This issue has been fixed.
