### ISSUE TITLE
export to bibtex

### ISSUE THREAD

**Issue by wuyoli** [typst/hayagriva#68]
Does a exporter tool for export to bibtex already exist? (preferably a cli program) I would like to use this with org-roam-bibtex in emacs. The export to bibtex would be needed because org-roam-bibtex only supports bibtex.

**Comment by Enivex** [comment]
You would probably be better served by simply keeping your bibliography as bibtex instead of converting back and forth

**Comment by yochem** [comment]
`$ hayagriva refs.yml references --format bibtex > references.bib`

**Comment by reknih** [comment]
Duplicate of #171
