### ISSUE TITLE
The field name "parent" might be confusing to people who have never worked with graphs

### ISSUE THREAD

**Issue by tmke8** [typst/hayagriva#69]
It's maybe too late to change this, but I think something like `contained-in`, `included-in`, `part-of` or `published-in` would be more intuitive? I think the word "parent" can evoke the impression of prior literature which this article is building upon (the metaphorical parentage of the article). It's also just a very unspecific term.

**Comment by reknih** [comment]
As you have said, it is too late to change this. I see it mainly as an issue with improving our documentation.
