### ISSUE TITLE
Error when converting Bibtex to Hayagriva

### ISSUE THREAD

**Issue by mihock** [typst/hayagriva#72]
There is a small error in the conversion from Bibtex to Hayagriva. Bibtex items of type `incollection` are converted to Hayagriva items of type `chapter`. However, they should be converted to type `anthos`. On the other hand, Bibtex items of type `inbook` are converted to Hayagriva items of type `anthos`. However, they should be converted to type `chapter`. Both Bibtex items are simply confused in the conversion, so output of the references of these types is wrong in Typst, at least with the APA style. I hope this is enough information to fix the error.

**Comment by zepinglee** [comment]
I seems that both `@inbook` and `@incollection` types from bib(la)tex matches CSL's `chapter` type and they should have no difference in the output.

https://github.com/typst/hayagriva/blob/8dce242de6366156eee2ea113584236883af6e66/src/csl/taxonomy.rs#L565-L567

> Both Bibtex items are simply confused in the conversion, so output of the references of these types is wrong in Typst, at least with the APA style.

Can you provide an example BibTeX entry and the expected output?

**Comment by mihock** [comment]
Here is a small example.

Testfile apatest.typ with two items. The only difference between the two items is that the Bibttex item type is `incollection` (which is correct) or `inbook` which is wrong in this case. With the source of the error, I was not quite correct:  The error seems to occur when the output is converted to pdf, not when the Bibtex file is converted to yml. 

Outputfile: 
[apatest.pdf](https://github.com/typst/hayagriva/files/13235538/apatest.pdf)

The first item (inbook) in the output shows how incollection items should be formatted with apa. The second item (incollection) is formatted in the wrong way.

Testfile:

```
The first item (incollection) should be formatted as an edited book. The correct citation of an edited book is only achieved if the Bibtex item is inbook, which is wrong for this citation.

- @alloy1990_incollection
- @alloy1990_inbook

#bibliography("apatest.yml",
  title: "References",
  style: "apa",
  )
```

Bibtex file:

```
@incollection{alloy1990_incollection,
  title = {incollection: Comorbidity of anxiety and depressive disorders: A helplessness-hopelessness perspective},
  booktitle = {Comorbidity of mood and anxiety disorders},
  author = {Alloy, L.B. and Kelly, K. and Mineka, S. and Clements, C.},
  editor = {Maser, J.D. and Cloninger, C.R.},
  date = {1990},
  pages = {499--543},
  publisher = {{American Psychiatric Press}},
  location = {{Washington, DC}},
  langid = {english}
}

@inbook{alloy1990_inbook,
  title = {inbook: Comorbidity of anxiety and depressive disorders: A helplessness-hopelessness perspective},
  booktitle = {Comorbidity of mood and anxiety disorders},
  author = {Alloy, L.B. and Kelly, K. and Mineka, S. and Clements, C.},
  editor = {Maser, J.D. and Cloninger, C.R.},
  date = {1990},
  pages = {499--543},
  publisher = {{American Psychiatric Press}},
  location = {{Washington, DC}},
  langid = {english}
}
```

Attachments: Please strip off the txt-Extension.

[apatest.typ.txt](https://github.com/typst/hayagriva/files/13235597/apatest.typ.txt)
[apatest.bib.txt](https://github.com/typst/hayagriva/files/13235599/apatest.bib.txt)

Best, Michael

**Comment by zepinglee** [comment]
> Here is a small example.
> 
> Testfile apatest.typ with two items. The only difference between the two items is that the Bibttex item type is `incollection` (which is correct) or `inbook` which is wrong in this case. With the source of the error, I was not quite correct: The error seems to occur when the output is converted to pdf, not when the Bibtex file is converted to yml.

The mappings of these types should work as expected.

https://github.com/typst/hayagriva/blob/8dce242de6366156eee2ea113584236883af6e66/src/interop.rs#L170-L171

> Outputfile: [apatest.pdf](https://github.com/typst/hayagriva/files/13235538/apatest.pdf)
> 
> The first item (inbook) in the output shows how incollection items should be formatted with apa. The second item (incollection) is formatted in the wrong way.

It seems that `EntryType::Anthos` is missing here and hayagriva cannot find a `container-title` for the `@incollection` (anthos) entry. The `apa.csl` incorrectly treats the entry as a standalone work (like `book`) and outputs the title in italic.

https://github.com/typst/hayagriva/blob/8dce242de6366156eee2ea113584236883af6e66/src/lib.rs#L735-L773

I'm happy to make a PR but I've not figured out how to test the modified code (as I'm newbie to Rust).

**Comment by reknih** [comment]
Just add an `EntryType::Anthos => retrieve_container(&[ ... ])` and put everything that might be a container to the anthos in there
