### ISSUE TITLE
Example file for formats does not exist

### ISSUE THREAD

**Issue by Henriquelay** [typst/hayagriva#97]
https://github.com/typst/hayagriva/blob/3e92ac83837914a0f1feeff63e50ed2faa1577a6/docs/file-format.md?plain=1#L3

`hayagriva/blob/main/tests/basic.yml` me to a 404 page. The file is indeed not there. It got removed in 77a6b39.

**Comment by MKDJr** [comment]
I believe this was fixed in PR https://github.com/typst/hayagriva/pull/121. Maybe this issue can be closed?

**Comment by PgBiel** [comment]
Yep, thank you!
